package com.gracefulwind.learnarms.reader.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.gracefulwind.learnarms.reader.db.BookInfo;
import com.gracefulwind.learnarms.reader.db.StudentBean;

import com.gracefulwind.learnarms.reader.greendao.BookInfoDao;
import com.gracefulwind.learnarms.reader.greendao.StudentBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookInfoDaoConfig;
    private final DaoConfig studentBeanDaoConfig;

    private final BookInfoDao bookInfoDao;
    private final StudentBeanDao studentBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookInfoDaoConfig = daoConfigMap.get(BookInfoDao.class).clone();
        bookInfoDaoConfig.initIdentityScope(type);

        studentBeanDaoConfig = daoConfigMap.get(StudentBeanDao.class).clone();
        studentBeanDaoConfig.initIdentityScope(type);

        bookInfoDao = new BookInfoDao(bookInfoDaoConfig, this);
        studentBeanDao = new StudentBeanDao(studentBeanDaoConfig, this);

        registerDao(BookInfo.class, bookInfoDao);
        registerDao(StudentBean.class, studentBeanDao);
    }
    
    public void clear() {
        bookInfoDaoConfig.clearIdentityScope();
        studentBeanDaoConfig.clearIdentityScope();
    }

    public BookInfoDao getBookInfoDao() {
        return bookInfoDao;
    }

    public StudentBeanDao getStudentBeanDao() {
        return studentBeanDao;
    }

}
